(function(g){var window=this;'use strict';var nhb=function(a){g.T.call(this,{G:"div",N:"ytp-inline-preview-ui"});this.Zf=!1;this.player=a;this.S(a,"onStateChange",this.pP);this.S(a,"videodatachange",this.yw);this.S(a,"onInlinePreviewModeChange",this.W3);this.rf=new g.Gp(this.Iv,null,this);g.D(this,this.rf)},x6=function(a){g.oT.call(this,a);
this.j=new nhb(this.player);g.D(this,this.j);this.j.hide();g.ES(this.player,this.j.element,4);if(a.isInline()){this.load();var b=a.getRootNode();g.Rp(b,["ytp-inline-preview-mode","ytp-no-contextmenu"]);this.player.T().K("web_inline_player_disable_scrubbing")&&g.Up(a.getRootNode(),"ytp-inline-preview-mode-no-scrubbing",!0)}};
g.w(nhb,g.T);g.k=nhb.prototype;
g.k.vM=function(){this.tooltip=new g.XV(this.player,this);g.D(this,this.tooltip);g.ES(this.player,this.tooltip.element,4);this.tooltip.scale=.6;this.Rc=new g.UT(this.player);g.D(this,this.Rc);this.Wj=new g.T({G:"div",Ia:["ytp-inline-preview-scrim"]});g.D(this,this.Wj);this.Wj.Ea(this.element);this.S(this.Wj.element,"click",this.cH);this.uj=new g.QV(this.player,this,300);g.D(this,this.uj);this.uj.Ea(this.Wj.element);this.controls=new g.T({G:"div",N:"ytp-inline-preview-controls"});g.D(this,this.controls);
this.controls.Ea(this.element);var a=new g.WU(this.player,this,this.player.T().K("kevlar_simp_remove_min_width_for_mute_button"));g.D(this,a);a.Ea(this.controls.element);a=new g.OV(this.player,this);g.D(this,a);a.Ea(this.controls.element);this.Jc=new g.cV(this.player,this);g.D(this,this.Jc);g.ES(this.player,this.Jc.element,4);this.S(this.player,"appresize",this.Eb);this.S(this.player,"fullscreentoggled",this.Eb);this.Eb()};
g.k.show=function(){g.Hp(this.rf);this.Zf||(this.vM(),this.Zf=!0);0!==this.player.getPlayerState()&&g.T.prototype.show.call(this);this.Jc.show();this.player.Na("onInlinePreviewUiReady")};
g.k.hide=function(){this.rf.stop();g.T.prototype.hide.call(this);this.player.isInline()||this.Zf&&this.Jc.hide()};
g.k.oa=function(){g.T.prototype.oa.call(this)};
g.k.cH=function(a){a.target===this.Wj.element&&this.player.Na("onExpandInlinePreview",a)};
g.k.W3=function(){g.Up(this.player.getRootNode(),"ytp-inline-preview-mode",this.player.isInline())};
g.k.Je=function(){this.Jc.yc();this.uj.yc()};
g.k.Iv=function(){this.Je();g.Hp(this.rf)};
g.k.Eb=function(){g.pV(this.Jc,0,this.player.ib().getPlayerSize().width,!1);g.dV(this.Jc)};
g.k.pP=function(a){this.player.isInline()&&(0===a?this.hide():this.show())};
g.k.yw=function(a,b){if(this.player.isInline()){g.Up(this.player.getRootNode(),"ytp-show-inline-preview-audio-controls",b.aJ);var c,d,e;a=!(null==(e=null==(c=b.getPlayerResponse())?void 0:null==(d=c.playerConfig)?void 0:d.inlinePlaybackConfig)||!e.showScrubbingControls);g.Up(this.player.getRootNode(),"ytp-hide-inline-preview-progress-bar",!a)}};
g.k.Dc=function(){return this.tooltip};
g.k.vg=function(){return!1};
g.k.lh=function(){return!1};
g.k.Sb=function(){return!1};
g.k.Ql=function(){return!1};
g.k.SD=function(){};
g.k.Sp=function(){};
g.k.jy=function(){};
g.k.Om=function(){return null};
g.k.NF=function(){return null};
g.k.QF=function(){return new g.Fe(0,0)};
g.k.cC=function(){return null};
g.k.Dk=function(){return new g.Nm(0,0,0,0)};
g.k.handleGlobalKeyDown=function(){return!1};
g.k.handleGlobalKeyUp=function(){return!1};
g.k.Vv=function(a,b,c,d,e){var f=d=0,h=0,l=g.an(a);if(b){c=g.Pp(b,"ytp-mute-button");var m=g.Pp(b,"ytp-subtitles-button"),n=g.Zm(b,this.element);b=g.an(b);d=n.y+40;if(m||c)h=n.x-l.width+b.width}else h=c-l.width/2,f=35;b=this.player.ib().getPlayerSize().width;h=g.ye(h,0,b-l.width);d?(a.style.top=d+(e||0)+"px",a.style.bottom=""):(a.style.top="",a.style.bottom=f+"px");a.style.left=h+"px"};
g.k.showControls=function(){};
g.k.xp=function(){};
g.k.Kl=function(){return!1};
g.k.TD=function(){};
g.k.Qz=function(){};
g.k.Xq=function(){};
g.k.Wq=function(){};
g.k.ZA=function(){};
g.k.Wr=function(){};
g.k.ED=function(){};g.w(x6,g.oT);x6.prototype.Xk=function(){return!1};
x6.prototype.load=function(){this.player.hideControls();this.j.show()};
x6.prototype.unload=function(){this.player.showControls();this.j.hide()};g.nT("inline_preview",x6);})(_yt_player);
